baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'SDI - Synthetic Digital Immunity'
theme = 'book'

[params]
  # Book theme configuration
  BookTheme = "auto"  # auto, dark, light
  BookMenuBundle = "/menu"
  
  # Enable features
  BookSearch = true
  BookComments = false
  BookToC = true
  BookSectionNav = true
  
  # Branding
  BookLogo = "/images/logo.png"
  BookRepo = "https://github.com/skesani/sdi"
  
  # Code highlighting
  BookDateFormat = "January 2, 2006"
  BookPostDate = false

[markup]
  [markup.highlight]
    style = "github"
    codeFences = true
    lineNos = true
    noClasses = false

[menu]
  [[menu.main]]
    identifier = "getting-started"
    name = "Getting Started"
    url = "/getting-started/"
    weight = 1
  
  [[menu.main]]
    identifier = "java"
    name = "Java"
    url = "/java/"
    weight = 2
  
  [[menu.main]]
    identifier = "python"
    name = "Python"
    url = "/python/"
    weight = 3
  
  [[menu.main]]
    identifier = "nodejs"
    name = "Node.js"
    url = "/nodejs/"
    weight = 4
  
  [[menu.main]]
    identifier = "go"
    name = "Go"
    url = "/go/"
    weight = 5
  
  [[menu.main]]
    identifier = "api"
    name = "API Reference"
    url = "/api/"
    weight = 6
